"""Add multi-tenancy: Store model and store_id columns

Revision ID: 45a6a1913a89
Revises:
Create Date: 2026-07-27

Written by hand (not autogenerated) to safely upgrade an EXISTING
single-tenant database (e.g. current Render production) to the new
multi-tenant schema.

Everything here is idempotent (IF NOT EXISTS / IF EXISTS) on purpose:
app.py's init_db() calls db.create_all() on every process start (including
the one triggered by `flask db upgrade` importing app.py itself), and
create_all() will already create the brand-new `stores` table straight from
the current models before this migration's own statements run. All ADD
COLUMN statements use nullable=True, so this is safe to run against a
database that already has rows - application code (app.py init_db()
bootstrap) backfills store_id for pre-existing rows on next startup.
"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '45a6a1913a89'
down_revision = None
branch_labels = None
depends_on = None


TABLES_WITH_STORE_ID = [
    "images",
    "categories",
    "products",
    "orders",
    "order_items",
    "site_settings",
    "contact_messages",
    "blog_posts",
    "blog_plans",
    "ai_settings",
    "users",
]


def upgrade():
    op.execute("""
        CREATE TABLE IF NOT EXISTS stores (
            id SERIAL PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            slug VARCHAR(63) NOT NULL,
            owner_user_id INTEGER NOT NULL REFERENCES users (id),
            plan VARCHAR(30) NOT NULL DEFAULT 'starter',
            subscription_status VARCHAR(20) NOT NULL DEFAULT 'trialing',
            stripe_customer_id VARCHAR(255),
            stripe_subscription_id VARCHAR(255),
            trial_ends_at TIMESTAMP,
            is_active BOOLEAN DEFAULT TRUE,
            created_at TIMESTAMP,
            updated_at TIMESTAMP,
            CONSTRAINT uq_stores_slug UNIQUE (slug)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_stores_slug ON stores (slug)")

    for table in TABLES_WITH_STORE_ID:
        op.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS store_id INTEGER")
        op.execute(f"CREATE INDEX IF NOT EXISTS ix_{table}_store_id ON {table} (store_id)")
        op.execute(f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_{table}_store_id_stores'
                      AND conrelid = '{table}'::regclass
                ) THEN
                    ALTER TABLE {table}
                        ADD CONSTRAINT fk_{table}_store_id_stores
                        FOREIGN KEY (store_id) REFERENCES stores (id);
                END IF;
            END $$;
        """)

    # Старі глобальні unique-обмеження (sku/slug унікальні по всій платформі)
    # блокують ту саму назву в різних магазинах - замінюємо на композитні
    # (унікальність в межах store_id). Назви старих constraint - дефолтні
    # Postgres-імена для unique=True без явного name (<table>_<column>_key);
    # DROP CONSTRAINT IF EXISTS безпечний, якщо назва відрізняється в
    # конкретному деплої - просто нічого не видалить.
    op.execute("ALTER TABLE products DROP CONSTRAINT IF EXISTS products_sku_key")
    op.execute("ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_slug_key")
    op.execute("ALTER TABLE blog_posts DROP CONSTRAINT IF EXISTS blog_posts_slug_key")

    # ВАЖЛИВО: перевірки нижче зумисно прив'язані до конкретної таблиці через
    # conrelid = '<table>'::regclass (яке резолвиться з урахуванням поточного
    # search_path) - бо conname у pg_constraint НЕ унікальне по всій базі, і
    # без цього уточнення перевірка може хибно "знайти" однойменний constraint
    # в іншій Postgres-схемі (наприклад, іншого store/деплою) і помилково
    # пропустити створення в поточній.
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_products_store_sku' AND conrelid = 'products'::regclass
            ) THEN
                ALTER TABLE products ADD CONSTRAINT uq_products_store_sku UNIQUE (store_id, sku);
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_categories_store_slug' AND conrelid = 'categories'::regclass
            ) THEN
                ALTER TABLE categories ADD CONSTRAINT uq_categories_store_slug UNIQUE (store_id, slug);
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_blog_posts_store_slug' AND conrelid = 'blog_posts'::regclass
            ) THEN
                ALTER TABLE blog_posts ADD CONSTRAINT uq_blog_posts_store_slug UNIQUE (store_id, slug);
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_site_settings_store_id' AND conrelid = 'site_settings'::regclass
            ) THEN
                ALTER TABLE site_settings ADD CONSTRAINT uq_site_settings_store_id UNIQUE (store_id);
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_ai_settings_store_id' AND conrelid = 'ai_settings'::regclass
            ) THEN
                ALTER TABLE ai_settings ADD CONSTRAINT uq_ai_settings_store_id UNIQUE (store_id);
            END IF;
        END $$;
    """)


def downgrade():
    op.execute("ALTER TABLE ai_settings DROP CONSTRAINT IF EXISTS uq_ai_settings_store_id")
    op.execute("ALTER TABLE site_settings DROP CONSTRAINT IF EXISTS uq_site_settings_store_id")
    op.execute("ALTER TABLE blog_posts DROP CONSTRAINT IF EXISTS uq_blog_posts_store_slug")
    op.execute("ALTER TABLE categories DROP CONSTRAINT IF EXISTS uq_categories_store_slug")
    op.execute("ALTER TABLE products DROP CONSTRAINT IF EXISTS uq_products_store_sku")

    op.execute("ALTER TABLE blog_posts ADD CONSTRAINT blog_posts_slug_key UNIQUE (slug)")
    op.execute("ALTER TABLE categories ADD CONSTRAINT categories_slug_key UNIQUE (slug)")
    op.execute("ALTER TABLE products ADD CONSTRAINT products_sku_key UNIQUE (sku)")

    for table in TABLES_WITH_STORE_ID:
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS fk_{table}_store_id_stores")
        op.execute(f"DROP INDEX IF EXISTS ix_{table}_store_id")
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS store_id")

    op.execute("DROP INDEX IF EXISTS ix_stores_slug")
    op.execute("DROP TABLE IF EXISTS stores")
